import { EngineResult } from '@commitguard/core';
import { Severity } from '@commitguard/shared';

export class PRSummaryGenerator {
  static generate(result: EngineResult): string {
    const icon = result.status === Severity.PASS ? '✅' : result.status === Severity.WARNING ? '⚠️' : '🚫';
    let summary = `## ${icon} CommitGuard Policy Report\n\n`;
    summary += `| | |\n|---|---|\n`;
    summary += `| **Status** | ${result.status} |\n`;
    summary += `| **Risk Score** | ${result.score} / 100 |\n\n`;

    const violations = result.results.filter(r => r.status !== Severity.PASS);

    if (violations.length === 0) {
      summary += `> ✅ All policy checks passed — this commit is clean.\n`;
      return summary;
    }

    summary += `### Violations (${violations.length})\n\n`;
    summary += `| Severity | Validator | Details | Fix |\n`;
    summary += `|---|---|---|---|\n`;

    for (const v of violations) {
      const vIcon = v.status === Severity.WARNING ? '⚠️' : '🚫';
      const name = v.validatorName ?? '';
      const details = v.violations && v.violations.length > 0
        ? v.violations.slice(0, 3).map(x => `\`${x.file}:${x.line}\` — ${x.match}`).join('<br/>')
        : v.message.replace(/\n/g, ' ');
      summary += `| ${vIcon} ${v.status} | ${name} | ${details} | ${v.remediation.split('\n')[0]} |\n`;
    }

    summary += `\n---\n*Generated by [CommitGuard](https://github.com/svjkumar89/commitguard)*\n`;
    return summary;
  }
}
